<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="8" failures="0" file="logger_tests.py" name="logger_tests.SimulationTester-20191219113254" skipped="0" tests="9" time="0.029" timestamp="2019-12-19T11:32:54">
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="29" name="test_writecsv" time="0.004" timestamp="2019-12-19T11:32:54">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'str'&gt;]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'str' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'str' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'list'&gt;]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'list' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'list' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'int'&gt;]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'int' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'int' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'list'&gt;]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'list' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'list' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'bool'&gt;]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'bool' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'bool' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'list'&gt;]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'list' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'list' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'float'&gt;]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error message="'float' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'float' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="logger_tests.SimulationTester" file="tests/logger_tests.py" line="14" name="test_writeimg [raises_type_exception_on_invalid_value_type_&lt;class 'list'&gt;]" time="0.025" timestamp="2019-12-19T11:32:54">
		<error message="'list' object has no attribute '__array_interface__'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/thizzhead/sim-duckietown/tests/logger_tests.py", line 27, in test_writeimg
    self.sut.writeimg("test1", v)
  File "/home/thizzhead/sim-duckietown/logger.py", line 97, in writeimg
    img = Image.fromarray(img)
  File "/home/thizzhead/.local/lib/python3.7/site-packages/PIL/Image.py", line 2638, in fromarray
    arr = obj.__array_interface__
AttributeError: 'list' object has no attribute '__array_interface__'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
